{
    "metadata": {
        "kernelspec": {
            "name": "SQL",
            "display_name": "SQL",
            "language": "sql"
        },
        "language_info": {
            "name": "sql",
            "version": ""
        }
    },
    "nbformat_minor": 2,
    "nbformat": 4,
    "cells": [
        {
            "cell_type": "code",
            "source": [
                "--Q10- Create Users, Roles and Logins according to 3 Roles: Admin, HR, and Employee.\n",
                "--Admin can view full database and has full access, HR can view and access only employee and offices table. --Employee can view all tables only.\n",
                "\n",
                "\n",
                "--Create Roles--\n",
                "\n",
                "Create role admin;\n",
                "Create role HR;\n",
                "Create role employee;\n",
                "\n",
                "--Create logins with password--\n",
                "\n",
                "Create login Dianetest1 with password = 'Diane123';\n",
                "Create login Marytest1 with password = 'Mary123';\n",
                "Create login Jefftest1 with password = 'Jeff123';\n",
                "create login Williamtest1 with password = 'William123';\n",
                "create login Gerardtest with password = 'Gerard123';\n",
                "create login Anthonytest1 with password = 'Anthony123';\n",
                "create login Leslietest1 with password = 'Leslie123';\n",
                "create login LeslieTtest1 with password = 'LeslieT123';\n",
                "create login Julietest1 with password = 'Julie123';\n",
                "create login Stevetest1 with password = 'Steve123';\n",
                "create login FoonYuetest1 with password = 'FoonYue123';\n",
                "create login Georgetest1 with password = 'George123';\n",
                "create login Louitest1 with password = 'Loui123';\n",
                "create login GerardHtest1 with password = 'GerardH123';\n",
                "create login Pamelatest1 with password = 'Pamela123';\n",
                "create login Larrytest1 with password = 'Larry123';\n",
                "create login Barrytest1 with password = 'Barry123';\n",
                "create login Andytest1 with password = 'Andy123';\n",
                "create login Petertest1 with password = 'Peter123';\n",
                "create login Tomtest1 with password = 'Tom123';\n",
                "create login Mamitest1 with password = 'Mami123';\n",
                "create login Yoshimitest1 with password = 'Yoshimi123';\n",
                "create login Martintets1 with password = 'Martin123';\n",
                "--Create Users and assign them to roles--\n",
                "\n",
                "USE MotorsCertificatiion;\n",
                "\n",
                "Create user Dianetestuser for login Dianetest1;\n",
                "Create user Marytestuser for login Marytest1; \n",
                "Create user Jefftestuser for login Jefftest1;\n",
                "create user Williamtestuser for login Williamtest1;\n",
                "create user Gerardtestuser for login Gerardtest;\n",
                "create user Anthonytestuser for login Anthonytest1;\n",
                "create user Leslietestuser for login Leslietest1;\n",
                "create user LeslieTtestuser for login LeslieTtest1;\n",
                "create user Julietestuser for login Julietest1;\n",
                "create user Stevetestuser for login Stevetest1;\n",
                "create user FoonYuetestuser for login FoonYuetest1;\n",
                "create user Georgetestuser for login Georgetest1;\n",
                "create user Louitestuser for login Louitest1;\n",
                "create user GerardHtestuser for login GerardHtest1;\n",
                "create user Pamelatestuser for login Pamelatest1;\n",
                "create user Larrytestuser for login Larrytest1;\n",
                "create user Barrytestuser for login Barrytest1;\n",
                "create user  Andytestuser for login Andytest1;\n",
                "create user Petertestuser for login Petertest1;\n",
                "create user Tomtestuser for login Tomtest1;\n",
                "create user Mamitestuser for login Mamitest1;\n",
                "create user Yoshimitestuser for login Yoshimitest1;\n",
                "create user Martintetsuser for login Martintets1;\n",
                "Alter role Admin add member Dianetestuser;\n",
                "Alter role\tHR add member Marytestuser; \n",
                "Alter role\tHR add member Jefftestuser;\n",
                "\n",
                "alter role employee add member Williamtestuser;\n",
                "\n",
                "alter role employee add member Gerardtestuser;\n",
                "alter role employee add member Anthonytestuser;\n",
                "alter role employee add member Leslietestuser;\n",
                "alter role employee add member LeslieTtestuser;\n",
                "alter role employee add member Julietestuser;\n",
                "alter role employee add member Stevetestuser;\n",
                "alter role employee add member FoonYuetestuser;\n",
                "alter role employee add member Georgetestuser;\n",
                "alter role employee add member Louitestuser;\n",
                "alter role employee add member GerardHtestuser;\n",
                "alter role employee add member Pamelatestuser;\n",
                "alter role employee add member Larrytestuser;\n",
                "alter role employee add member Barrytestuser;\n",
                "alter role employee add member Andytestuser;\n",
                "alter role employee add member Petertestuser;\n",
                "alter role employee add member Tomtestuser;\n",
                "alter role employee add member Mamitestuser;\n",
                "alter role employee add member Yoshimitestuser;\n",
                "alter role employee add member Martintetsuser;\n",
                "\n",
                "\n",
                "--Grant permission--\n",
                "--Admin has full access to the enrire database--\n",
                "\n",
                "Grant control on database::Motorscertificatiion To admin;\n",
                "--Hr can access only employees table and offices table--\n",
                "\n",
                "Grant SELECT, INSERT, UPDATE, DELETE ON dbo.employee to HR;\n",
                "Grant SELECT, INSERT, UPDATE, DELETE ON dbo.offices to HR;\n",
                "\n",
                "\n",
                "--employee can view all table--\n",
                "\n",
                "Grant SELECT on database::motorscertificatiion to employee;\n",
                ""
            ],
            "metadata": {
                "azdata_cell_guid": "5e7f7874-b6d2-4b92-a23c-dd3fdb32ce71",
                "language": "sql"
            },
            "outputs": [],
            "execution_count": null
        }
    ]
}